// <auto-generated />
using System;
using CarRental.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRental.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // ── Branch ────────────────────────────────────────────────
            modelBuilder.Entity("CarRental.Domain.Entities.Branch", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("City").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Address").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
                b.Property<string>("Phone").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<int?>("ManagerId").HasColumnType("int");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("Name");
                b.HasIndex("City");
                b.HasIndex("ManagerId");
                b.ToTable("Branches");
            });

            // ── User ──────────────────────────────────────────────────
            modelBuilder.Entity("CarRental.Domain.Entities.User", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");
                b.Property<string>("Username").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("PasswordHash").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("FullName").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                b.Property<string>("Phone").HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<int>("Role").HasColumnType("int");
                b.Property<int?>("BranchId").HasColumnType("int");
                b.Property<int?>("CreatedByUserId").HasColumnType("int");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<bool>("IsLocked").HasColumnType("bit");
                b.Property<int>("FailedLoginAttempts").HasColumnType("int");
                b.Property<DateTime?>("LockedUntil").HasColumnType("datetime2");
                b.Property<DateTime?>("LastActivityAt").HasColumnType("datetime2");
                b.Property<DateTime?>("LastLoginAt").HasColumnType("datetime2");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("Username").IsUnique();
                b.HasIndex("Email").IsUnique();
                b.HasIndex("Role");
                b.HasIndex("BranchId");
                b.ToTable("Users");
            });

            // ── Vehicle ───────────────────────────────────────────────
            modelBuilder.Entity("CarRental.Domain.Entities.Vehicle", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");
                b.Property<string>("RegistrationNumber").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<int>("BranchId").HasColumnType("int");
                b.Property<int>("AddedByUserId").HasColumnType("int");
                b.Property<string>("Brand").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Model").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<int>("Year").HasColumnType("int");
                b.Property<int>("Category").HasColumnType("int");
                b.Property<decimal>("DailyRate").HasColumnType("decimal(10,2)");
                b.Property<int>("Status").HasColumnType("int");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<bool>("IsOffer").HasColumnType("bit");
                b.Property<int?>("DiscountPercent").HasColumnType("int");
                b.Property<string>("ColorHex").HasMaxLength(10).HasColumnType("nvarchar(10)");
                b.Property<string>("FuelType").HasMaxLength(30).HasColumnType("nvarchar(30)");
                b.Property<string>("Transmission").HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<int?>("Seats").HasColumnType("int");
                b.Property<decimal?>("Rating").HasColumnType("decimal(3,2)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("RegistrationNumber").IsUnique();
                b.HasIndex("Category");
                b.HasIndex("BranchId");
                b.HasIndex("Status");
                b.ToTable("Vehicles");
            });

            // ── Client ────────────────────────────────────────────────
            modelBuilder.Entity("CarRental.Domain.Entities.Client", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");
                b.Property<string>("FullName").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Phone").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<string>("Address").HasMaxLength(300).HasColumnType("nvarchar(300)");
                b.Property<bool>("IsFlagged").HasColumnType("bit");
                b.Property<string>("FlagReason").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.HasIndex("Phone").IsUnique();
                b.HasIndex("FullName");
                b.ToTable("Clients");
            });

            // ── Rental ────────────────────────────────────────────────
            modelBuilder.Entity("CarRental.Domain.Entities.Rental", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");
                b.Property<int>("VehicleId").HasColumnType("int");
                b.Property<int>("ClientId").HasColumnType("int");
                b.Property<int>("BranchId").HasColumnType("int");
                b.Property<int>("CreatedByUserId").HasColumnType("int");
                b.Property<int?>("CompletedByUserId").HasColumnType("int");
                b.Property<string>("BookingReference").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<DateTime>("StartDate").HasColumnType("datetime2");
                b.Property<DateTime>("EndDate").HasColumnType("datetime2");
                b.Property<string>("PickupLocation").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("ReturnLocation").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<decimal>("TotalCost").HasColumnType("decimal(10,2)");
                b.Property<int>("Status").HasColumnType("int");
                b.Property<string>("CancellationReason").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<string>("ProtectionPlan").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("Extras").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<string>("Notes").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                b.Property<bool>("PayNow").HasColumnType("bit");
                b.Property<byte[]>("RowVersion").IsRowVersion().IsConcurrencyToken().HasColumnType("rowversion");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("BookingReference").IsUnique();
                b.HasIndex("VehicleId");
                b.HasIndex("ClientId");
                b.HasIndex("BranchId");
                b.HasIndex("Status");
                b.ToTable("Rentals");
            });

            // ── RefreshToken ──────────────────────────────────────────
            modelBuilder.Entity("CarRental.Domain.Entities.RefreshToken", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");
                b.Property<int>("UserId").HasColumnType("int");
                b.Property<string>("Token").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<DateTime>("ExpiresAt").HasColumnType("datetime2");
                b.Property<bool>("IsRevoked").HasColumnType("bit");
                b.Property<DateTime?>("RevokedAt").HasColumnType("datetime2");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("Token").IsUnique();
                b.HasIndex("UserId");
                b.ToTable("RefreshTokens");
            });

            // ── AuditLog ──────────────────────────────────────────────
            modelBuilder.Entity("CarRental.Domain.Entities.AuditLog", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");
                b.Property<int?>("UserId").HasColumnType("int");
                b.Property<string>("EntityType").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<int>("EntityId").HasColumnType("int");
                b.Property<string>("Action").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Details").IsRequired().HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                b.Property<DateTime>("Timestamp").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.HasIndex("Timestamp");
                b.ToTable("AuditLogs");
            });

            // ── SecurityAlert ─────────────────────────────────────────
            modelBuilder.Entity("CarRental.Domain.Entities.SecurityAlert", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:Identity", "1, 1");
                b.Property<int>("UserId").HasColumnType("int");
                b.Property<int>("AlertType").HasColumnType("int");
                b.Property<string>("Description").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<bool>("IsRead").HasColumnType("bit");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.HasIndex("IsRead");
                b.ToTable("SecurityAlerts");
            });

            // ── Relationships ─────────────────────────────────────────
            modelBuilder.Entity("CarRental.Domain.Entities.Branch", b =>
            {
                b.HasOne("CarRental.Domain.Entities.User", "Manager")
                    .WithMany()
                    .HasForeignKey("ManagerId")
                    .OnDelete(DeleteBehavior.SetNull);
                b.Navigation("Manager");
            });

            modelBuilder.Entity("CarRental.Domain.Entities.User", b =>
            {
                b.HasOne("CarRental.Domain.Entities.Branch", "Branch")
                    .WithMany("Staff")
                    .HasForeignKey("BranchId")
                    .OnDelete(DeleteBehavior.SetNull);
                b.HasOne("CarRental.Domain.Entities.User", "CreatedByUser")
                    .WithMany()
                    .HasForeignKey("CreatedByUserId")
                    .OnDelete(DeleteBehavior.NoAction);
                b.Navigation("Branch");
                b.Navigation("CreatedByUser");
            });

            modelBuilder.Entity("CarRental.Domain.Entities.Vehicle", b =>
            {
                b.HasOne("CarRental.Domain.Entities.Branch", "Branch")
                    .WithMany("Vehicles")
                    .HasForeignKey("BranchId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.HasOne("CarRental.Domain.Entities.User", "AddedByUser")
                    .WithMany("AddedVehicles")
                    .HasForeignKey("AddedByUserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("Branch");
                b.Navigation("AddedByUser");
            });

            modelBuilder.Entity("CarRental.Domain.Entities.Rental", b =>
            {
                b.HasOne("CarRental.Domain.Entities.Vehicle", "Vehicle")
                    .WithMany("Rentals")
                    .HasForeignKey("VehicleId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.HasOne("CarRental.Domain.Entities.Client", "Client")
                    .WithMany("Rentals")
                    .HasForeignKey("ClientId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.HasOne("CarRental.Domain.Entities.Branch", "Branch")
                    .WithMany("Rentals")
                    .HasForeignKey("BranchId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.HasOne("CarRental.Domain.Entities.User", "CreatedByUser")
                    .WithMany("CreatedRentals")
                    .HasForeignKey("CreatedByUserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.HasOne("CarRental.Domain.Entities.User", "CompletedByUser")
                    .WithMany("CompletedRentals")
                    .HasForeignKey("CompletedByUserId")
                    .OnDelete(DeleteBehavior.SetNull);
                b.Navigation("Vehicle");
                b.Navigation("Client");
                b.Navigation("Branch");
                b.Navigation("CreatedByUser");
                b.Navigation("CompletedByUser");
            });

            modelBuilder.Entity("CarRental.Domain.Entities.RefreshToken", b =>
            {
                b.HasOne("CarRental.Domain.Entities.User", "User")
                    .WithMany("RefreshTokens")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("User");
            });

            modelBuilder.Entity("CarRental.Domain.Entities.AuditLog", b =>
            {
                b.HasOne("CarRental.Domain.Entities.User", "User")
                    .WithMany("AuditLogs")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.SetNull);
                b.Navigation("User");
            });

            modelBuilder.Entity("CarRental.Domain.Entities.SecurityAlert", b =>
            {
                b.HasOne("CarRental.Domain.Entities.User", "User")
                    .WithMany("SecurityAlerts")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("User");
            });

            // ── Navigations ───────────────────────────────────────────
            modelBuilder.Entity("CarRental.Domain.Entities.Branch", b =>
            {
                b.Navigation("Vehicles");
                b.Navigation("Staff");
                b.Navigation("Rentals");
            });

            modelBuilder.Entity("CarRental.Domain.Entities.User", b =>
            {
                b.Navigation("CreatedRentals");
                b.Navigation("CompletedRentals");
                b.Navigation("AddedVehicles");
                b.Navigation("RefreshTokens");
                b.Navigation("AuditLogs");
                b.Navigation("SecurityAlerts");
            });

            modelBuilder.Entity("CarRental.Domain.Entities.Vehicle", b =>
            {
                b.Navigation("Rentals");
            });

            modelBuilder.Entity("CarRental.Domain.Entities.Client", b =>
            {
                b.Navigation("Rentals");
            });
#pragma warning restore 612, 618
        }
    }
}
